apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: cards-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: banking-microservices
        property: CARDS_DB_HOST
    - secretKey: DB_NAME
      remoteRef:
        key: banking-microservices
        property: CARDS_DB_NAME
    - secretKey: DB_USERNAME
      remoteRef:
        key: banking-microservices
        property: CARDS_DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: banking-microservices
        property: CARDS_DB_PASS
