apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accounts
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: banking-microservices
    app.kubernetes.io/component: accounts
spec:
  project: default
  source:
    repoURL: https://github.com/roylohhh/IaC-microservices-on-AWS-EKS
    targetRevision: main
    path: helm/accounts
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
